import { StyleSheet } from "react-native";
import { Colors } from "react-native/Libraries/NewAppScreen";

export const MyColor = {
  white: '#fff',
  black: '#000',
  gray1: '#444444',
  gray2: '#888888',
  gray3: '#cccccc',
  highlight: '#78aac2',
  gray4: '#f1f1f1',
  red1: '#ff1111',
  red2: '#ff0000',
  red3: '#8c0000',
  button: '#78aac2',
  buttonred: '#8c0000',
  // your colors
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    //backgroundColor: "#ff0000",
    justifyContent: "space-between",
    flexDirection: "column",
  },
  containerRow: {
    flex: 1,
    flexDirection: "row",
  },
  scrollView: {
    backgroundColor: Colors.lighter,
  },
  sectionContainer: {
    paddingHorizontal: 24,
    paddingVertical: 48,
    //backgroundColor: "#00FF00",
  },
  sectionContainerButton: {
    paddingHorizontal: 24,
    paddingVertical: 24,
    paddingBottom: 48,
    //backgroundColor: "#00FF00",
  },
  sectionTitle: {
    fontSize: 32,
    fontWeight: "600",
    color: MyColor.black,
    marginBottom: 20,
  },
  sectionTitlewoNav: {
    fontSize: 32,
    fontWeight: "600",
    color: MyColor.black,
    marginBottom: 20,
    paddingTop: 32,
  },
  sectionTitlewoNavWhite: {
    fontSize: 32,
    fontWeight: "600",
    color: MyColor.white,
    marginBottom: 20,
    paddingTop: 32,
  },
  sectionSubtitle: {
    fontSize: 14,
    fontWeight: "800",
    color: MyColor.highlight,
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: "400",
    color: MyColor.gray1,
  },
  sectionOption: {
    marginTop: 20,
    fontSize: 14,
    fontWeight: "400",
    color: MyColor.gray1,
    textAlign: "center",
  },
  sectionTitleWhite: {
    fontSize: 32,
    fontWeight: "600",
    color: MyColor.white,
    marginBottom: 20,
  },
  footer: {
    color: MyColor.gray1,
    fontSize: 12,
    fontWeight: "600",
    padding: 4,
    paddingRight: 12,
    textAlign: "right",
  },
  maincard: {
    maxWidth: 500,
    width: "100%",
    margin: "auto",
    marginTop: 15,
    marginBottom: 15,
    padding: 20,
    borderRadius: 10,
    backgroundColor: MyColor.white,
    shadowColor: MyColor.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  textbox: {
    color: MyColor.black,
    width: "100%",
    marginTop: 5,
    marginBottom: 0,
    height: 44,
    borderBottomColor: MyColor.gray4,
    borderBottomWidth: 1,
  },
  textboxerror: {
    color: MyColor.black,
    width: "100%",
    marginTop: 5,
    marginBottom: 0,
    height: 44,
    borderBottomColor: MyColor.red1,
    borderBottomWidth: 1,
  },
  texterror: {
    paddingTop: 5,
    paddingLeft: 5,
    fontSize: 10,
    color: MyColor.red2,
  },
  button: {
    borderWidth: 1,
    borderColor: MyColor.button,
    backgroundColor: MyColor.button,
    borderRadius: 4,
    width: "100%",
    marginTop: 10,
    height: 44,
    justifyContent: "center",
  },
  buttonText: {
    color: MyColor.white,
    textAlign: "center",
    fontWeight: "600",
    fontSize: 16,
  },
  buttonbdr: {
    borderWidth: 1,
    borderColor: MyColor.button,
    borderRadius: 4,
    width: "100%",
    marginTop: 10,
    height: 44,
    justifyContent: "center",
  },
  buttonbdrText: {
    color: MyColor.button,
    textAlign: "center",
    fontWeight: "600",
    fontSize: 16,
  },
  buttonfilter: {
    borderWidth: 1,
    borderColor: MyColor.button,
    borderRadius: 4,
    width: "100%",
    marginTop: 10,
    height: 38,
    justifyContent: "center",
  },
  buttonbdrRed: {
    borderWidth: 1,
    borderColor: MyColor.buttonred,
    borderRadius: 4,
    width: "100%",
    marginTop: 10,
    marginBottom: 0,
    padding: 10,
  },
  buttonTextRed: {
    color: MyColor.buttonred,
    textAlign: "center",
    fontWeight: "600",
    fontSize: 16,
  },
  buttonWhite: {
    borderWidth: 1,
    borderColor: MyColor.white,
    backgroundColor: MyColor.white,
    borderRadius: 4,
    width: "100%",
    marginTop: 10,
    height: 44,
    justifyContent: "center",
  },
  buttonTextWhite: {
    color: MyColor.black,
    textAlign: "center",
    fontWeight: "600",
    fontSize: 16,
  },
  buttonbdrWhite: {
    borderWidth: 1,
    borderColor: MyColor.white,
    borderRadius: 4,
    width: "100%",
    marginTop: 10,
    height: 44,
    justifyContent: "center",
  },
  buttonbdrTextWhite: {
    color: MyColor.white,
    textAlign: "center",
    fontWeight: "600",
    fontSize: 16,
  },
  textbold: {
    fontWeight: "600",
  },
  pic: {
    width: "100%",
    height: "100%",
    justifyContent: "space-between",
  },

  //AccessCard Page
  cardHeader: {
    fontSize: 20,
    fontWeight: "600",
    color: Colors.black,
    marginBottom: 10,
  },
  cardHeaderColor: {
    fontSize: 18,
    fontWeight: "600",
    color: MyColor.highlight,
    marginBottom: 5,
  },
  cardTitle: {
    fontSize: 32,
    fontWeight: "600",
    color: MyColor.black,
  },
  cardSubtitle: {
    fontSize: 12,
    fontWeight: "800",
    color: MyColor.highlight,
  },
  cardDes: {
    fontSize: 12,
    color: Colors.dark,
  },
  itemcard: {
    borderRadius: 10,
    backgroundColor: MyColor.white,
    shadowColor: MyColor.black,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 5,
    height: 140,
    maxWidth: 500,
    width: "100%",
    margin: "auto",
    marginTop: 20,
    // overflow: "hidden",
    // padding: 20,
  },

  //Access page
  accessSearchItem1: {
    paddingRight: 10,
    width: "70%",
  },
  accessSearchItem2: {
    width: "30%",
  },
  accessCard: {
    borderRadius: 20,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    backgroundColor: MyColor.white,
  },
  accessContainer: {
    paddingHorizontal: 24,
    paddingVertical: 24,
    paddingBottom: 48,
    //backgroundColor: "#00FF00",
  },
  accessImageContainer: {
    paddingHorizontal: 24,
    paddingTop: 96,
  },
  shareImageContainer: {
    paddingTop: 80,
  },
  shareColContainer: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  shareCol40: {
    width: "40%",
    alignItems: "center",
  },
  shareCol60: {
    width: "60%",
    paddingTop: 32,
    height: 132,
    justifyContent: "center",
  },
  shareTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: MyColor.white,
  },
  shareSubtitle: {
    fontSize: 14,
    fontWeight: "400",
    color: MyColor.white,
    marginBottom: 20,
  },
  sharePicOuter: {
    shadowColor: MyColor.black,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.51,
    shadowRadius: 13.16,
    elevation: 20,
  },
  sharePic: {
    borderRadius: 4,
    width: 100,
    height: 100,
    margin: 20,
  },

  //Other page
  otherAvatar: {
    width: 100,
    height: 100,
    borderRadius: 100,
    resizeMode: "stretch",
  },
  otherCenterBlock: {
    alignItems: "center",
  },
  otherTitle: {
    marginTop: 10,
    fontSize: 20,
    fontWeight: "600",
    textAlign: "center",
    color: MyColor.black,
  },
  otherDes: {
    fontSize: 12,
    fontWeight: "400",
    color: MyColor.black,
    textAlign: "center",
  },
  otherMenuTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: MyColor.black,
  },
  otherMenuTitleRed: {
    fontSize: 15,
    fontWeight: "600",
    color: MyColor.red3,
  },
  otherMenuTitleBlue: {
    fontSize: 15,
    fontWeight: "600",
    color: "#003366",
  },
  otherMenuDes: {
    fontSize: 12,
    fontWeight: "400",
    color: MyColor.gray1,
  },
  otherMenu: {
    marginVertical: 15,
    //paddingHorizontal: 15,
  },
  otherMenuRed: {
    marginVertical: 15,
    //paddingHorizontal: 15,
  },

  //Homeuser
  homeuserBalanceCard: {
    maxWidth: 500,
    width: "100%",
    margin: "auto",
    marginTop: 10,
    marginBottom: 30,
    padding: 30,
    borderRadius: 10,
    backgroundColor: MyColor.white,
    shadowColor: MyColor.gray2,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  homeuserShortcutBlock: {
    height: 100,
  },
  homeuserColContainer: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  homeuserCol33: {
    width: "33%",
    alignItems: "center",
  },
  homeuserShortcutCard: {
    height: 100,
    width: "90%",
    margin: "auto",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 10,
    backgroundColor: MyColor.white,
    shadowColor: MyColor.gray2,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 5,
  },
  homeuserShortcutData: {
    height: 100,
    width: "100%",
    padding: 10,
    margin: "auto",
    alignItems: "center",
    justifyContent: "space-between",
  },
  homeuserTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: Colors.black,
    marginTop: 25,
    marginBottom: 20,
  },
  homeuserCardTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: Colors.white,
  },
  homeuserCardSubtitle: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.white,
  },
  homeuserIcon: {
    height: 50,
    width: 70,
    borderRadius: 0,
    resizeMode: "stretch",
  },

  //License
  licenseTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: MyColor.black,
  },
  licenseProvince: {
    fontSize: 12,
    fontWeight: "400",
    color: MyColor.gray2,
  },
  licenseCard: {
    maxWidth: 500,
    width: "100%",
    margin: "auto",
    marginTop: 10,
    marginBottom: 10,
    padding: 20,
    borderRadius: 10,
    backgroundColor: MyColor.white,
    shadowColor: MyColor.gray2,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
    alignItems: "center",
  },
  licenseCardBorder: {
    maxWidth: 500,
    width: "100%",
    margin: "auto",
    marginTop: 10,
    marginBottom: 10,
    padding: 20,
    borderRadius: 10,
    borderColor: MyColor.highlight,
    borderWidth: 3,
    backgroundColor: MyColor.white,
    shadowColor: MyColor.gray2,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
    alignItems: "center",
  },
  licenseColContainer: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  licenseCol30: {
    width: "30%",
    paddingRight: 10,
  },
  licenseCol40: {
    width: "40%",
    paddingRight: 10,
    justifyContent: "center",
    height: 70,
  },
  licenseCol60: {
    width: "60%",
    paddingLeft: 10,
    justifyContent: "center",
    height: 70,
  },
  licenseCol70: {
    width: "70%",
    paddingLeft: 10,
  },
  licenseBlock: {
    height: 70,
  },
  licenseCardBlock: {
    height: 70,
  },
  licensePlateIcon: {
    height: 70,
    width: 98,
    borderRadius: 0,
    resizeMode: "stretch",
  },

  //Payment
  paymentTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: MyColor.black,
  },
  paymentExpire: {
    fontSize: 12,
    fontWeight: "400",
    color: MyColor.gray2,
  },
  paymentCard: {
    maxWidth: 500,
    width: "100%",
    margin: "auto",
    marginTop: 10,
    marginBottom: 10,
    padding: 20,
    borderRadius: 10,
    backgroundColor: MyColor.white,
    shadowColor: MyColor.gray2,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
    alignItems: "center",
  },
  paymentCardBorder: {
    maxWidth: 500,
    width: "100%",
    margin: "auto",
    marginTop: 10,
    marginBottom: 10,
    padding: 20,
    borderRadius: 10,
    borderColor: MyColor.highlight,
    borderWidth: 3,
    backgroundColor: MyColor.white,
    shadowColor: MyColor.gray2,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
    alignItems: "center",
  },
  paymentCardBlock: {
    height: 70,
  },
  paymentColContainer: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  paymentCol30: {
    width: "30%",
    paddingRight: 10,
    justifyContent: "center",
    height: 70,
  },
  paymentCol70: {
    width: "70%",
    paddingLeft: 20,
    justifyContent: "center",
    height: 70,
  },
  paymentIcon: {
    height: 70,
    width: 98,
    borderRadius: 0,
    resizeMode: "stretch",
  },
});

module.exports = styles;
